# ==================================================================================
# ARCHITECTURAL MODES:
# 1. STAGING (8M Rows): Set strategy=tag_all & external_id=Row_Id__c
#    -> Use to preserve full history. (SF: Row_Id__c MUST be ExtID/Unique)
# 2. CLEANUP (Merge):  Set strategy=unique_only & external_id=Composite_Key__c
#    -> Use to deduplicate on-the-fly. (SF: Composite_Key__c MUST be ExtID)
#
# REQUIRED SALESFORCE FIELDS:
# - Row_Id__c: Text(255), External ID, Unique (Case-Insensitive)
# - Composite_Key__c: Text(255), External ID (Do NOT mark as Unique)
# - IsDuplicate__c: Checkbox (Default: False)
# ==================================================================================

[SALESFORCE]
instance_url = https://login.salesforce.com(your login url)
username = your_user@example.com
password = your_password
token = your_security_token else leave blank without any quotes(token = )

[DATA]
input_file = data/poc_data.csv
log_file = logs/migration_log.csv
batch_size = 10000
target_object = Account

# KEY CONFIGURATION:
# Use 'Row_Id__c' to insert all 8M rows. 
# Use 'Composite_Key__c' to merge duplicates into 1 record.
external_id = Row_Id__c

# DEDUPLICATION SETTINGS:
# 'tag_all'     = Upload everything, flag duplicates as True.
# 'unique_only' = Upload only the first occurrence, skip others.
strategy = unique_only

# The logic used to identify duplicates (Field names must match CSV headers)
unique_key_rule = {FirstName}_{LastName}_{DOB}
duplicate_indicator_field = IsDuplicate__c
composite_key_field = Composite_Key__c

[MAPPING]
# Format: Salesforce_Field_API_Name = CSV_Header_Name or {Template}
# Note: Fields containing 'Date' will be auto-formatted to YYYY-MM-DD
Name                 = {FirstName} {LastName}
Phone                = Phone
SLAExpirationDate__c = DOB